----------------------------------

# <span style="color:blueviolet"> 👩‍💻 DATA EDA <span style ="font-family:Papyrus;"> with python </span>
----------------------------------

<span style="background-color:#F5F5F5"> **🚩 강의 개요** <br> </span> 
- python 이 어떠한 언어인지 이해합니다. 
- python 의 library 의 개념을 이해하고 실습합니다. 
- kaggle dataset 을 활용한 전반적인 EDA 를 진행합니다.
- 모든 회차에서 실습 코드를 제공합니다.
- 이론 비중 30%, 코드실습 비중 70%

<span style="background-color:#F5F5F5"> **🚩 커리큘럼** <br> </span> 
- 1회차: python, 라이브러리 개념학습 및 실습환경 준비
- 2회차: python 활용 테이블 결합 + 과제
- 3회차: python 활용 데이터 이상치, 결측치 처리
- 4회차: python 활용 데이터 시각화 + 과제
- 5회차: 그 외 주요 라이브러리 살펴보기
- 6회차: 2, 4회차 과제해설
</span> 
  

-----------------------------------

## <span style="color:red"> 📌 chapter 1. python 과 라이브러리의 이해

#### <span style="color:blue"> **📘 1-1. 라이브러리 import** </span>

In [6]:
import pandas as pd
import numpy as np
import time
from PIL import Image

#### <span style="color:blue"> **📘 1-2. 라이브러리 지원 함수 살펴보기** </span>

In [5]:
#설명을 위해 이미지를 캡쳐하여 업로드 하였습니다.
Image.open('func.png')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/jun/GitStudy/Data_4/src/study/func.png'

In [1]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
sum([1,2,3])

6

In [3]:
%%time 
sum1=0
for x in range(10000000) :
    sum1=sum1+x

print("1부터 1000만까지 합 :",sum1)

1부터 1000만까지 합 : 49999995000000
CPU times: user 549 ms, sys: 7.93 ms, total: 557 ms
Wall time: 561 ms

---------------------------------

## <span style="color:red"> 📌 chapter 2. Pandas를 활용한 EDA 시작!

#### <span style="color:blue"> **📘 2-1. DataFrame(테이블) 만들기** </span>

In [7]:
# pandas 라이브러리를 활용한 dataframe 만들기 - List 활용
data1 = [['Choi',22],['Kim',48],['Joo',32]]
df4 = pd.DataFrame(data1, columns=['Name','Age'])

# pandas 라이브러리를 활용한 dataframe 만들기 - Dictionary 활용
data2 = {'Name' : ['Choi','Kim','Joo'],'Age':[22,48,32]}
df5 = pd.DataFrame(data2)

In [16]:
df5

   Name  Age
0  Choi   22
1   Kim   48
2   Joo   32

#### <span style="color:blue"> **📘 2-2. CSV 파일을 통한 테이블 LOAD** </span>

In [34]:

import kagglehub, os, shutil
data_dir = '/Users/jun/GitStudy/Data_4/Data'
ecommerce_dir = os.path.join(data_dir,"eCommerce2")


if os.path.exists(ecommerce_dir):
    print("exsist")
else:
    os.mkdir(ecommerce_dir)

'''
# Download latest version
path = kagglehub.dataset_download("datascientist97/e-commerece-sales-data-2024")
print("Path to dataset files:", path)

os.chdir(path)
file_list = os.listdir()

for i in file_list:
    file_path = os.path.join(path,i)
    shutil.move(file_path, ecommerce_dir)

cache_dir = "~.cache/kagglehub"
if os.path.exists(cache_dir):
    shutil.rmtree(cache_dir)
'''

exsist

'\n# Download latest version\npath = kagglehub.dataset_download("datascientist97/e-commerece-sales-data-2024")\nprint("Path to dataset files:", path)\n\nos.chdir(path)\nfile_list = os.listdir()\n\nfor i in file_list:\n    file_path = os.path.join(path,i)\n    shutil.move(file_path, ecommerce_dir)\n\ncache_dir = "~.cache/kagglehub"\nif os.path.exists(cache_dir):\n    shutil.rmtree(cache_dir)\n'

In [35]:
os.chdir(ecommerce_dir)

In [36]:
# pandas 라이브러리를 활용한 csv 파일 읽기 
df = pd.read_csv("product_details.csv") # product_details.csv
df2 = pd.read_csv("customer_details.csv") # customer_details.csv
df3 = pd.read_csv("E-commerece sales data 2024.csv") # E-commerece sales data 2024.csv

#### <span style="color:blue"> **📘 2-3. 테이블 확인하기** </span>

In [37]:
# 테이블은 어떻게 생겼을까요?
display(df, df2, df3)
#하나의 테이블을 가져올 땐, display 를 사용하지 않고 바로 호출해도 됩니다. :) 
# 처음 5 줄만 출력하기 
#df2.head()
# 마지막 5 줄만 출력하기 
#df2.tail()

,Uniqe Id,Product Name,Brand Name,Asin,Category,Upc Ean Code,List Price,Selling Price,Quantity,Model Number,...,Product Url,Stock,Product Details,Dimensions,Color,Ingredients,Direction To Use,Is Amazon Seller,Size Quantity Variant,Product Description
0,4c69b61db1fc16e7013b43fc926e502d,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",NaN,NaN,Sports & Outdoors | Outdoor Recreation | Skate...,NaN,NaN,$237.68,NaN,NaN,...,https://www.amazon.com/DB-Longboards-CoreFlex-...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
1,66d49bbed043f5be260fa9f7fbff5957,"Electronic Snap Circuits Mini Kits Classpack, ...",NaN,NaN,Toys & Games | Learning & Education | Science ...,NaN,NaN,$99.95,NaN,55324,...,https://www.amazon.com/Electronic-Circuits-Cla...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
2,2c55cae269aebf53838484b0d7dd931a,3Doodler Create Flexy 3D Printing Filament Ref...,NaN,NaN,Toys & Games | Arts & Crafts | Craft Kits,NaN,NaN,$34.99,NaN,NaN,...,https://www.amazon.com/3Doodler-Plastic-Innova...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
3,18018b6bc416dab347b1b7db79994afa,Guillow Airplane Design Studio with Travel Cas...,NaN,NaN,Toys & Games | Hobbies | Models & Model Kits |...,NaN,NaN,$28.91,NaN,142,...,https://www.amazon.com/Guillow-Airplane-Design...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
4,e04b990e95bf73bbe6a3fa09785d7cd0,Woodstock- Collage 500 pc Puzzle,NaN,NaN,Toys & Games | Puzzles | Jigsaw Puzzles,NaN,NaN,$17.49,NaN,62151,...,https://www.amazon.com/Woodstock-Collage-500-p...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,1a22f23576bfdfe5ed6c887dc117aab6,Remedia Publications REM536B Money Activity Bo...,NaN,NaN,Toys & Games | Learning & Education | Counting...,NaN,NaN,$9.31,NaN,REM536B,...,https://www.amazon.com/Remedia-Publications-RE...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
9998,e11514dcf1f087887cd5ea0bd646d1fc,Trends International NFL La Chargers HG - Mobi...,NaN,NaN,Toys & Games | Arts & Crafts,NaN,NaN,$6.99,NaN,NaN,...,https://www.amazon.com/Trends-International-NF...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
9999,c00301a38560da2abc89c1f86ce4b267,NewPath Learning 10 Piece Science Owls and Owl...,NaN,NaN,Office Products | Office & School Supplies | E...,NaN,NaN,$37.95,NaN,34-6015,...,https://www.amazon.com/NewPath-Learning-Scienc...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
10000,c2928dbf9796ceba44863a2736afb405,Disney Princess Do It Yourself Braid Set,NaN,NaN,Toys & Games | Arts & Crafts | Craft Kits,NaN,NaN,$3.58,NaN,2888PRST,...,https://www.amazon.com/Disney-Princess-Yoursel...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
10001,2bb94aefc3467ed83860e0e2712d5f10,"Hasegawa Ladders Lucano Step Ladder, Orange",NaN,NaN,Home & Kitchen | Furniture | Kids' Furniture |...,NaN,NaN,$152.27,NaN,ML2.0-4OR,...,https://www.amazon.com/Hasegawa-Ladders-Lucano...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

,user id,product id,Interaction type,Time stamp,Unnamed: 4
0,1.0,4c69b61db1fc16e7013b43fc926e502d,purchase,10/10/2023 8:00,NaN
1,2.0,66d49bbed043f5be260fa9f7fbff5957,view,11/10/2023 8:00,NaN
2,3.0,2c55cae269aebf53838484b0d7dd931a,like,12/10/2023 8:00,NaN
3,4.0,18018b6bc416dab347b1b7db79994afa,view,13/10/2023 8:00,NaN
4,5.0,e04b990e95bf73bbe6a3fa09785d7cd0,like,14/10/2023 8:00,NaN
...,...,...,...,...,...
3289,NaN,NaN,NaN,NaN,NaN
3290,NaN,NaN,NaN,NaN,NaN
3291,NaN,NaN,NaN,NaN,NaN
3292,NaN,NaN,NaN,NaN,NaN
3293,NaN,NaN,NaN,NaN,NaN

#### <span style="color:blue"> **📘 2-4. 테이블 구조 파악하기** </span>

In [38]:
# 각 테이블의 행(가로) 길이 파악하기
len(df), len(df2), len(df3)

(10002, 3900, 3294)

In [39]:
# 테이블의 데이터 구조를 파악하는 다양한 방법
# shape: 테이블의 행과 열의 갯수를 반환 
# dtypes: 테이블 내 컬럼타입(문자형, 숫자형, 배열 등) 확인
# columns: 테이블 내 컬럼 확인
# values: 테이블 내 각 행들을 배열 형태로 확인
"테이블 열과 행 갯수",df.shape,"테이블 컬럼 타입",df.dtypes,"테이블 컬럼 확인", df.columns,"테이블 행 상세확인", df.values

('테이블 열과 행 갯수',
 (10002, 28),
 '테이블 컬럼 타입',
 Uniqe Id                  object
 Product Name              object
 Brand Name               float64
 Asin                     float64
 Category                  object
 Upc Ean Code              object
 List Price               float64
 Selling Price             object
 Quantity                 float64
 Model Number              object
 About Product             object
 Product Specification     object
 Technical Details         object
 Shipping Weight           object
 Product Dimensions        object
 Image                     object
 Variants                  object
 Sku                      float64
 Product Url               object
 Stock                    float64
 Product Details          float64
 Dimensions               float64
 Color                    float64
 Ingredients              float64
 Direction To Use         float64
 Is Amazon Seller          object
 Size Quantity Variant    float64
 Product Description      float64
 dtype: object,
 '테이블 컬럼 확인',
 Index(['Uniqe Id', 'Product Name', 'Brand Name', 'Asin', 'Category',
        'Upc Ean Code', 'List Price', 'Selling Price', 'Quantity',
        'Model Number', 'About Product', 'Product Specification',
        'Technical Details', 'Shipping Weight', 'Product Dimensions', 'Image',
        'Variants', 'Sku', 'Product Url', 'Stock', 'Product Details',
        'Dimensions', 'Color', 'Ingredients', 'Direction To Use',
        'Is Amazon Seller', 'Size Quantity Variant', 'Product Description'],
       dtype='object'),
 '테이블 행 상세확인',
 array([['4c69b61db1fc16e7013b43fc926e502d',
         'DB Longboards CoreFlex Crossbow 41" Bamboo Fiberglass Longboard Complete',
         nan, ..., 'Y', nan, nan],
        ['66d49bbed043f5be260fa9f7fbff5957',
         'Electronic Snap Circuits Mini Kits Classpack, FM Radio, Motion Detector, Music Box (Set of 5)',
         nan, ..., 'Y', nan, nan],
        ['2c55cae269aebf53838484b0d7dd931a',
         "3Doodler Create Flexy 3D Printing Filament Refill Bundle (X5 Pack, Over 1000'. of Extruded Plastics! - Innovate",
         nan, ..., 'Y', nan, nan],
        ...,
        ['c00301a38560da2abc89c1f86ce4b267',
         'NewPath Learning 10 Piece Science Owls and Owl Pellets Curriculum Mastery Flip Chart Set, Grade 5-9',
         nan, ..., 'Y', nan, nan],
        ['c2928dbf9796ceba44863a2736afb405',
         'Disney Princess Do It Yourself Braid Set', nan, ..., 'Y', nan,
         nan],
        ['2bb94aefc3467ed83860e0e2712d5f10',
         'Hasegawa Ladders Lucano Step Ladder, Orange', nan, ..., 'Y',
         nan, nan]], dtype=object))

In [40]:
#테이블 컬럼을 리스트로 확인하기 
df.columns.to_list()

['Uniqe Id',
 'Product Name',
 'Brand Name',
 'Asin',
 'Category',
 'Upc Ean Code',
 'List Price',
 'Selling Price',
 'Quantity',
 'Model Number',
 'About Product',
 'Product Specification',
 'Technical Details',
 'Shipping Weight',
 'Product Dimensions',
 'Image',
 'Variants',
 'Sku',
 'Product Url',
 'Stock',
 'Product Details',
 'Dimensions',
 'Color',
 'Ingredients',
 'Direction To Use',
 'Is Amazon Seller',
 'Size Quantity Variant',
 'Product Description']

In [41]:
# 테이블 기본 구조 한눈에 확인하기
# 컬럼의 타입과 결측치 데이터 타입 확인가능 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Uniqe Id               10002 non-null  object
 1   Product Name           10002 non-null  object
 2   Brand Name             0 non-null      float64
 3   Asin                   0 non-null      float64
 4   Category               9172 non-null   object
 5   Upc Ean Code           34 non-null     object
 6   List Price             0 non-null      float64
 7   Selling Price          9895 non-null   object
 8   Quantity               0 non-null      float64
 9   Model Number           8230 non-null   object
 10  About Product          9729 non-null   object
 11  Product Specification  8370 non-null   object
 12  Technical Details      9212 non-null   object
 13  Shipping Weight        8864 non-null   object
 14  Product Dimensions     479 non-null    object
 15  Image                  10002 non-null  object
 16  Variants               2478 non-null   object
 17  Sku                    0 non-null      float64
 18  Product Url            10002 non-null  object
 19  Stock                  0 non-null      float64
 20  Product Details        0 non-null      float64
 21  Dimensions             0 non-null      float64
 22  Color                  0 non-null      float64
 23  Ingredients            0 non-null      float64
 24  Direction To Use       0 non-null      float64
 25  Is Amazon Seller       10002 non-null  object
 26  Size Quantity Variant  0 non-null      float64
 27  Product Description    0 non-null      float64
dtypes: float64(13), object(15)
memory usage: 2.1+ MB

In [42]:
# 테이블 행렬전환
df.T

,0,1,2,3,4,5,6,7,8,9,...,9992,9993,9994,9995,9996,9997,9998,9999,10000,10001
Uniqe Id,4c69b61db1fc16e7013b43fc926e502d,66d49bbed043f5be260fa9f7fbff5957,2c55cae269aebf53838484b0d7dd931a,18018b6bc416dab347b1b7db79994afa,e04b990e95bf73bbe6a3fa09785d7cd0,f8c32a45e507a177992973cf0d46d20c,40d3cd16b41970ae6872e914aecf2c8e,bc178f33a04dbccefa95b165f8b56830,cc2083338a16c3fe2f7895289d2e98fe,69828c5570dcdbd1609216d33fbad0db,...,ed6e3e3888c8acd0f2a43fb3e960aaa5,5952d531555fb032835aa7e821865314,b9d06a48b902ba45f73ff1db4b2790bd,ec8506d9915fb21052be5a529e32f61e,0678767f2ff24c5c2330ed0d4456c199,1a22f23576bfdfe5ed6c887dc117aab6,e11514dcf1f087887cd5ea0bd646d1fc,c00301a38560da2abc89c1f86ce4b267,c2928dbf9796ceba44863a2736afb405,2bb94aefc3467ed83860e0e2712d5f10
Product Name,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...","Electronic Snap Circuits Mini Kits Classpack, ...",3Doodler Create Flexy 3D Printing Filament Ref...,Guillow Airplane Design Studio with Travel Cas...,Woodstock- Collage 500 pc Puzzle,"Terra by Battat – 4 Dinosaur Toys, Medium – Di...",Rubie's Child's Pokemon Deluxe Pikachu Costume...,Hoffmaster 120813 Double-Tipped Triangular Cra...,"ARTSCAPE Etched Glass 24"" x 36"" Window Film, 2...",Pokemon TCG: Sun and Moon Crimson Invasion Eli...,...,"REALBUG Scarlet Plant Bug Bracelet, Clear",DRESS MY CRAFT/CRAFTER'S 3PL DMCMA10893A Minia...,Mega Construx Despicable Me Micro Action Figur...,Cozy Line Home Fashions Size 2 Piece Ocean Cre...,"LEGO 8-Brick Storage Box, Bright Red",Remedia Publications REM536B Money Activity Bo...,Trends International NFL La Chargers HG - Mobi...,NewPath Learning 10 Piece Science Owls and Owl...,Disney Princess Do It Yourself Braid Set,"Hasegawa Ladders Lucano Step Ladder, Orange"
Brand Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Asin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,Sports & Outdoors | Outdoor Recreation | Skate...,Toys & Games | Learning & Education | Science ...,Toys & Games | Arts & Crafts | Craft Kits,Toys & Games | Hobbies | Models & Model Kits |...,Toys & Games | Puzzles | Jigsaw Puzzles,NaN,"Clothing, Shoes & Jewelry | Costumes & Accesso...",Toys & Games | Arts & Crafts | Drawing & Paint...,Home & Kitchen | Home Décor | Window Treatment...,NaN,...,Toys & Games | Novelty & Gag Toys,Toys & Games | Toy Figures & Playsets | Action...,Toys & Games | Building Toys | Building Sets,Home & Kitchen | Bedding | Kids' Bedding | Qui...,Toys & Games | Building Toys,Toys & Games | Learning & Education | Counting...,Toys & Games | Arts & Crafts,Office Products | Office & School Supplies | E...,Toys & Games | Arts & Crafts | Craft Kits,Home & Kitchen | Furniture | Kids' Furniture |...
Upc Ean Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
List Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Selling Price,$237.68,$99.95,$34.99,$28.91,$17.49,$18.66,$29.12,$97.68,$12.99,$38.49,...,$11.69,$12.76,$30.21,$77.89,$24.98,$9.31,$6.99,$37.95,$3.58,$152.27
Quantity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Model Number,NaN,55324,NaN,142,62151,AN4054Z,B07BZJM592,NaN,01-0121,820650802607-1,...,SL04,DMCMA10893A,FNC80,BB010057781,40041730,REM536B,NaN,34-6015,2888PRST,ML2.0-4OR
About Product,Make sure this fits by entering your model num...,Make sure this fits by entering your model num...,Make sure this fits by entering your model num...,Make 8 different Planes at one time. | Experim...,Make sure this fits by entering your model num...,Make sure this fits by entering your model num...,Make sure this fits by entering your model num...,NaN,Make sure this fits by entering your model num...,Make sure this fits by entering your model num...,...,Make sure this fits by entering your model num...,Craft SuppliesMINIATURE BOY,Make sure this fits by entering your model num...,Make sure this fits by entering your model num...,Make sure this fits by entering your model num...,NaN,Make sure this fits by entering your model num...,Make sure this fits by entering your model num...,NaN,Make sure this fits by entering your model num...
Product Specification,Shipping Weight: 10.7 pounds (View shipping ra...,Product Dimensions: 14.7 x 11.1 x 10.2...,ProductDimensions:10.3x3.4x0.8inches|ItemWeigh...,ProductDimensions:3.5x6.2x13inches|ItemWeight:...,ProductDimensions:1.9x8x10inches|ItemWeight:13...,ProductDimensions:8.7x3.9x3.4inches|ItemWeight...,ProductDimensions:16x8x1inches|ItemWeight:1pou...,NaN,ProductDimensions:72x36x0inches|ItemWeight:11....,ProductDimensions:7.5x3.5x6.8inches|ItemWeight...,...,ProductDimensions:1.2x0.8x0.5inches|ItemWeight...,ProductDimensions:3.2x3.2x1inches|ShippingWeig...,ProductDimensions:0.6x3.9x5.5inches|ItemWeight...,ProductDimensions:86x66x1inches|ItemWeight:6po...,ProductDimensions:19.7x9.8x7.1inches|ItemWeigh...,Product Dimensions: 11 x 8.5 x 0.4 inc...,ProductDimensions:3x6.5x0.3inches|ItemWeight:0...,Product Dimensions: 18 x 11.9 x 0.7 in...,ProductDimensions:7x7x2inches|ItemWeight:6.1ou...,ProductDimensions:22.8x6x64.2inches|ItemWeight...
Technical Details,NaN,The snap circuits mini kits classpack provides...,show up to 2 reviews by default No longer are ...,Go to your orders and start the return Select ...,show up to 2 reviews by default 100% Officiall...,Go to your orders and start the return Select ...,Go to your orders and start the return Select ...,NaN,show up to 2 reviews by default Product Descri...,show up to 2 reviews by default Crimson Choas ...,...,Product Description This bracelet has a REAL s...,5.1 ounces (View shipping rates and policies) ...,Go to your orders and start the return Select ...,Cozy Line Home Fashions is a well established ...,Go to your orders and start the return Select ...,show up to 2 reviews by default Activities inc...,The mobile wallet is made of silicone with str...,show up to 2 reviews by default NewPath Learni...,Disney Princess DIY Braid Set | 6.1 ounces (Vi...,Go to your orders and start the return Select ...
Shipping Weight,10.7 pounds,4 pounds,12.8 ounces,13.4 ounces,13.4 ounces,1.4 pounds,9.8 ounces,NaN,12.2 ounces,1.5 pounds,...,0.16 ounces,5.1 ounces,0.8 ounces,6.3 pounds,4.65 pounds,4.8 ounces,0.96 ounces,2.8 pounds,6.1 ounces,20.5 pounds
Product Dimensions,NaN,14.7 x 11.1 x 10.2 inches 4.06 pounds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11 x 8.5 x 0.4 inches 1.6 ounces,NaN,18 x 11.9 x 0.7 inches 2.75 pounds,NaN,NaN
Image,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...
Variants,https://www.amazon.com/DB-Longboards-CoreFlex-...,NaN,NaN,NaN,NaN,NaN,https://www.amazon.com/Rubies-Deluxe-Pikachu-P...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.amazon.com/LEGO-Storage-Brick-Brig...,NaN,NaN,NaN,NaN,https://www.amazon.com/Hasegawa-Ladders-Lucano...
Sku,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Url,https://www.amazon.com/DB-Longboards-CoreFlex-...,https://www.amazon.com/Electronic-Circuits-Cla...,https://www.amazon.com/3Doodler-Plastic-Innova...,https://www.amazon.com/Guillow-Airplane-Design...,https://www.amazon.com/Woodstock-Collage-500-p...,https://www.amazon.com/Terra-Battat-Dinosaurs-...,https://www.amazon.com/Rubies-Deluxe-Pikachu-P...,https://www.amazon.com/Hoffmaster-120813-Doubl...,https://www.amazon.com/ARTSCAPE-Etched-Glass-W...,https://www.amazon.com/Pokemon-TCG-Crimson-Inv...,...,https://www.amazon.com/REALBUG-Scarlet-Plant-B...,https://www.amazon.com/DRESS-CRAFT-CRAFTERS-3P...,https://www.amazon.com/Mega-Construx-Despicabl...,https://www.amazon.com/Cozy-Line-Home-Fashions...,https://www.amazon.com/LEGO-Storage-Brick-Brig...,https://www.amazon.com/Remedia-Publications-RE...,https://www.amazon.com/Trends-International-NF...,https://www.amazon.com/NewPath-Learning-Scienc...,https://www.amazon.com/Disney-Princess-Yoursel...,https://www.amazon.com/Hasegawa-Ladders-Lucano...
Stock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Details,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dimensions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Color,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ingredients,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Direction To Use,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Is Amazon Seller,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,Y,Y,Y,N,Y,Y,Y,Y,Y,Y
Size Quantity Variant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Description,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# 전체 행 갯수, 평균, 표준편차, 최솟값, 사분위수, 최댓값 확인 
df2.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

#### <span style="color:blue"> **📘 2-5. 테이블 결측치 확인하기** </span>

In [44]:
#컬럼별로 결측치(데이터가 없는) 확인하기 
df.isna().sum()
df.isnull().sum() # 동일한 기능

Uniqe Id                     0
Product Name                 0
Brand Name               10002
Asin                     10002
Category                   830
Upc Ean Code              9968
List Price               10002
Selling Price              107
Quantity                 10002
Model Number              1772
About Product              273
Product Specification     1632
Technical Details          790
Shipping Weight           1138
Product Dimensions        9523
Image                        0
Variants                  7524
Sku                      10002
Product Url                  0
Stock                    10002
Product Details          10002
Dimensions               10002
Color                    10002
Ingredients              10002
Direction To Use         10002
Is Amazon Seller             0
Size Quantity Variant    10002
Product Description      10002
dtype: int64

#### <span style="color:blue"> **📘 2-5. 특정 컬럼 1개 가져오기** </span>

In [45]:
#방법1: 속성. 사용
df.Category
#방법2: [] 연산자 사용
df['Category']
#방법3: iloc 사용
# : 은 모든 행을 가져오겠다는 의미이며 dataframe 의 인덱스 번호 4번(카테고리)컬럼을 가져오겠다는 희미
df.iloc[:,4]

0        Sports & Outdoors | Outdoor Recreation | Skate...
1        Toys & Games | Learning & Education | Science ...
2                Toys & Games | Arts & Crafts | Craft Kits
3        Toys & Games | Hobbies | Models & Model Kits |...
4                  Toys & Games | Puzzles | Jigsaw Puzzles
                               ...
9997     Toys & Games | Learning & Education | Counting...
9998                          Toys & Games | Arts & Crafts
9999     Office Products | Office & School Supplies | E...
10000            Toys & Games | Arts & Crafts | Craft Kits
10001    Home & Kitchen | Furniture | Kids' Furniture |...
Name: Category, Length: 10002, dtype: object

#### <span style="color:blue"> **📘 2-6. 특정 컬럼 여러개 가져오기** </span>

In [46]:
#방법1: [[]] 연산자 사용
# []를 하나 사용하면 결과값이 series 형태로 반환되어 key error 가발생되며, [[]] 는 dataframe 으로 반환되어 에러가 나지 않습니다. 
df[['Category','Selling Price']]
#방법2: iloc 사용
# : 은 모든 행을 가져오겠다는 의미이며 dataframe 의 인덱스 번호 4번,7번 컬럼을 가져오겠다는 희미
df.iloc[:,[4,7]]

                                                Category Selling Price
0      Sports & Outdoors | Outdoor Recreation | Skate...       $237.68
1      Toys & Games | Learning & Education | Science ...        $99.95
2              Toys & Games | Arts & Crafts | Craft Kits        $34.99
3      Toys & Games | Hobbies | Models & Model Kits |...        $28.91
4                Toys & Games | Puzzles | Jigsaw Puzzles        $17.49
...                                                  ...           ...
9997   Toys & Games | Learning & Education | Counting...         $9.31
9998                        Toys & Games | Arts & Crafts         $6.99
9999   Office Products | Office & School Supplies | E...        $37.95
10000          Toys & Games | Arts & Crafts | Craft Kits         $3.58
10001  Home & Kitchen | Furniture | Kids' Furniture |...       $152.27

[10002 rows x 2 columns]

#### <span style="color:blue"> **📘 2-7. 특정 컬럼 버리기** </span>

In [47]:
df3

,user id,product id,Interaction type,Time stamp,Unnamed: 4
0,1.0,4c69b61db1fc16e7013b43fc926e502d,purchase,10/10/2023 8:00,NaN
1,2.0,66d49bbed043f5be260fa9f7fbff5957,view,11/10/2023 8:00,NaN
2,3.0,2c55cae269aebf53838484b0d7dd931a,like,12/10/2023 8:00,NaN
3,4.0,18018b6bc416dab347b1b7db79994afa,view,13/10/2023 8:00,NaN
4,5.0,e04b990e95bf73bbe6a3fa09785d7cd0,like,14/10/2023 8:00,NaN
...,...,...,...,...,...
3289,NaN,NaN,NaN,NaN,NaN
3290,NaN,NaN,NaN,NaN,NaN
3291,NaN,NaN,NaN,NaN,NaN
3292,NaN,NaN,NaN,NaN,NaN
3293,NaN,NaN,NaN,NaN,NaN

In [48]:
df3

,user id,product id,Interaction type,Time stamp,Unnamed: 4
0,1.0,4c69b61db1fc16e7013b43fc926e502d,purchase,10/10/2023 8:00,NaN
1,2.0,66d49bbed043f5be260fa9f7fbff5957,view,11/10/2023 8:00,NaN
2,3.0,2c55cae269aebf53838484b0d7dd931a,like,12/10/2023 8:00,NaN
3,4.0,18018b6bc416dab347b1b7db79994afa,view,13/10/2023 8:00,NaN
4,5.0,e04b990e95bf73bbe6a3fa09785d7cd0,like,14/10/2023 8:00,NaN
...,...,...,...,...,...
3289,NaN,NaN,NaN,NaN,NaN
3290,NaN,NaN,NaN,NaN,NaN
3291,NaN,NaN,NaN,NaN,NaN
3292,NaN,NaN,NaN,NaN,NaN
3293,NaN,NaN,NaN,NaN,NaN

#### <span style="color:blue"> **📘 2-8. 조건에 부합하는 데이터 가져오기1** </span>

In [50]:
#조건에 만족하는 행은 정상출력 ,아닌 행은 NaN 으로 반환 
df2.where(df2['Age']>50)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1.0,55.0,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14.0,Venmo,Fortnightly
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3896,3897.0,52.0,Female,Backpack,Accessories,49.0,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41.0,Bank Transfer,Bi-Weekly
3897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3899,3900.0,52.0,Female,Handbag,Accessories,81.0,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33.0,Venmo,Quarterly

#### <span style="color:blue"> **📘 2-9. 조건에 부합하는 데이터 가져오기2** </span>

In [51]:
# 조건에 부합하는 데이터만 가져오고 싶을 때 
mask = ((df2['Age']>50) & (df2['Gender']=='Male'))

In [52]:
df2[mask]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly
10,11,53,Male,Shoes,Footwear,34,Arkansas,L,Purple,Fall,4.1,Yes,Store Pickup,Yes,Yes,26,Bank Transfer,Bi-Weekly
12,13,61,Male,Coat,Outerwear,72,Delaware,M,Gold,Winter,4.5,Yes,Express,Yes,Yes,37,Venmo,Fortnightly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2633,2634,51,Male,Sunglasses,Accessories,90,Alaska,M,Purple,Fall,4.7,No,Next Day Air,No,No,32,Credit Card,Fortnightly
2635,2636,59,Male,Hoodie,Clothing,80,Colorado,XL,Peach,Spring,2.9,No,2-Day Shipping,No,No,34,PayPal,Fortnightly
2647,2648,60,Male,Shoes,Footwear,58,South Carolina,M,Red,Summer,3.3,No,2-Day Shipping,No,No,25,Debit Card,Annually
2648,2649,51,Male,Pants,Clothing,84,Illinois,M,Gray,Spring,3.9,No,Next Day Air,No,No,14,PayPal,Bi-Weekly
2651,2652,51,Male,Sneakers,Footwear,43,Tennessee,M,Cyan,Summer,4.6,No,Store Pickup,No,No,27,PayPal,Quarterly

#### <span style="color:blue"> **📘 2-9. 테이블 그루핑** </span>

예제를 통해 SQL 구문과 비교해봅시다!

**[예제1]: df2 테이블을 활용한 gender 기준 customer id count하기**

<br>
<span style="color:blue">
1. SQL 활용<br>
   select Gender, count(Customer ID)<br>
   from df2<br>
   group by Gender<br> </span><br>
<span style="color:red">
2. Python 활용<br>
df2.groupby('Gender')['Customer ID'].count() </span>

In [53]:
#직접 실행해봅시다!
df2.groupby('Gender')['Customer ID'].count()

Gender
Female    1248
Male      2652
Name: Customer ID, dtype: int64

-------------------------


**[예제2]: df2 테이블을 활용한 gender,Location 기준 customer id count하기**

<br>
<span style="color:blue">
1. SQL 활용<br>
   select Gender, Location, count(Customer ID)<br>
   from df2<br>
   group by Gender, Location<br> </span><br>
<span style="color:red">
2. Python 활용<br>
df2.groupby(['Gender','Location'])['Customer ID'].count() </span>

In [54]:
df2.groupby(['Gender','Location'])['Customer ID'].count()

Gender  Location
Female  Alabama          27
        Alaska           24
        Arizona          25
        Arkansas         25
        California       29
                         ..
Male    Virginia         53
        Washington       48
        West Virginia    58
        Wisconsin        50
        Wyoming          51
Name: Customer ID, Length: 100, dtype: int64

----------------------------


**[예제3]: df2 테이블을 활용한 Location 기준 Age distinct count하기**

<br>
<span style="color:blue">
1. SQL 활용<br>
   select Location, count(distinct Age)<br>
   from df2<br>
   group by Location<br> </span><br>
<span style="color:red">
2. Python 활용<br>
df2.groupby('Location')['Age'].nunique() </span>

In [55]:
# count는 중복제거를 하지 않고, unique 는 중복을 제거합니다. :) 
#df2.groupby('Location')['Age'].count()와 비교해 봅시다.! 
df2.groupby('Location')['Age'].nunique()

Location
Alabama           40
Alaska            41
Arizona           42
Arkansas          39
California        45
Colorado          39
Connecticut       39
Delaware          40
Florida           39
Georgia           43
Hawaii            31
Idaho             47
Illinois          38
Indiana           40
Iowa              35
Kansas            37
Kentucky          41
Louisiana         38
Maine             41
Maryland          40
Massachusetts     39
Michigan          39
Minnesota         41
Mississippi       42
Missouri          41
Montana           44
Nebraska          43
Nevada            42
New Hampshire     40
New Jersey        38
New Mexico        42
New York          45
North Carolina    38
North Dakota      41
Ohio              40
Oklahoma          40
Oregon            39
Pennsylvania      39
Rhode Island      35
South Carolina    40
South Dakota      41
Tennessee         46
Texas             37
Utah              41
Vermont           42
Virginia          38
Washington        41
West Virginia     41
Wisconsin         40
Wyoming           36
Name: Age, dtype: int64

----------------------------

**[예제4]: df2 테이블을 활용한 Location 기준 Age distinct count 및 정렬**

<br>
<span style="color:blue">
1. SQL 활용<br>
   select Location, count(distinct Age) as cnt <br>
   from df2<br>
   group by Location<br>
   order by cnt desc <br> </span><br>
<span style="color:red">
2. Python 활용<br>
df2.groupby('Location')['Age'].count().sort_values(ascending=False) </span>

In [56]:
#sort_valuse 사용시, ascending=True 는 오름차순, False 는 내림차순
df2.groupby('Location')['Age'].count().sort_values(ascending=False)

Location
Montana           96
California        95
Idaho             93
Illinois          92
Alabama           89
Minnesota         88
Nevada            87
Nebraska          87
New York          87
Delaware          86
Maryland          86
Vermont           85
Louisiana         84
North Dakota      83
New Mexico        81
West Virginia     81
Missouri          81
Mississippi       80
Georgia           79
Arkansas          79
Indiana           79
Kentucky          79
North Carolina    78
Connecticut       78
Ohio              77
Tennessee         77
Texas             77
Virginia          77
Maine             77
South Carolina    76
Oklahoma          75
Wisconsin         75
Colorado          75
Oregon            74
Pennsylvania      74
Washington        73
Michigan          73
Massachusetts     72
Alaska            72
New Hampshire     71
Utah              71
Wyoming           71
South Dakota      70
Iowa              69
Florida           68
New Jersey        67
Arizona           65
Hawaii            65
Kansas            63
Rhode Island      63
Name: Age, dtype: int64

----------------------------